baseURL: https://the-augmented-leadership-manifesto.github.io
languageCode: en-us
title: The Augmented Leadership Manifesto
module:
  imports:
  - path: github.com/alex-shpak/hugo-book
copyright: Robert Hopp, Otmar Jenner

author:
  name: "Rosho.World"
  email: "info@rosho.world"
  location: "Avignon, Bangkok, Yokohama"

params:
  BookSection: /
  BookTheme: auto
  BookRepo: https://github.com/alex-shpak/hugo-book
  ananke_socials:
  - name: github
    url: https://github.com/the-augmented-leadership-manifesto/the-augmented-leadership-manifesto.github.io
  - name: linkedin
    url: https://de.linkedin.com/company/rosho-world/
  - name: facebook
    url: https://www.facebook.com/AugmentedLeadership/
  - name: twitter
    url: https://twitter.com/RoshoWorld
